"""Section: the project document model — what files exist and what they hold."""

from __future__ import annotations

SECTION = """# Project document model

The project lives on disk as a per-slide folder layout::

    {project_id}/
    ├── project.json          ← root: canvas, theme, audio, captions, slides[]
    └── slides/
        ├── slide-0/
        │   ├── index.json    ← {duration, fields, assets, ...} (voiceover excluded)
        │   ├── index.html    ← bare <template> sub-composition
        │   ├── audio.mp3     ← edge-tts output (optional)
        │   └── audio.json    ← TTS metadata {textHash, duration, voice, ...}
        └── ...

The in-memory bundle the API serves combines these as ``{root, slides,
slideHtml}``. Each slide has:

- ``id``              — stable identifier (e.g. "slide-0")
- ``duration``        — seconds on screen
- ``fields``          — text/color values stamped into the HTML via __OVK_*__
                        tokens. Known field ids: title, body, caption, quote,
                        name, step, url, cta, bg_color, accent, image, logo,
                        avatar, video, audio, bg_image.
- ``assets``          — image refs (sha256:…)
- ``voiceover``       — {text, voice, rate, pitch, volume}; lives in audio.json,
                        regenerated by TTS.
- ``transition``      — per-slide transition override.

The root has ``canvas`` (1920×1080 @30fps), ``theme`` (caption_style, colors,
fonts), ``audio`` (music bed + voiceover), ``captions`` (the caption style
settings used by the karaoke overlay), and ``slides`` (ordered id list).

Stamping: layout HTML contains ``__OVK_TITLE__`` etc.; at render time each
token is replaced with the slide's field value. ``__OVK_SLIDE_ID__`` is the
structural token (the slide's own id, used in CSS selectors and GSAP)."""
